dist: trusty

language: cpp

compiler: gcc

os:
- linux

before_install:
 - sudo apt-get -qq update
    
script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j
    
notifications:
email: false
